version: '3'
services:
  svjis-app:
    image: berk76/svjis-app:latest
    ports:
    - 8080:8080
    environment:
      - DB_SERVER=svjis-db
      - DB_USERNAME=web
      - DB_PASSWORD=change-it
  svjis-db:
    image: jacobalberty/firebird:3.0.7
    ports:
      - 3050:3050
    environment:
      - ISC_PASSWORD=change-it
      - FIREBIRD_DATABASE=SVJIS_PRODUCTION
      - FIREBIRD_USER=web
      - FIREBIRD_PASSWORD=change-it
    volumes:
      - svjis-data:/firebird
  firebirdadmin:
    image: marianaldenhoevel/firebirdwebadmin:latest
    ports:
    - 8081:80
volumes:
  svjis-data:
    driver: local
