apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: svjis-pvc
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
