name: svjis-app image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Change directory
      run: cd svjis-app
    - name: Build the Docker image
      run: docker build -t berk76/svjis-app:latest .
    - name: Docker Hub Login
      run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push
      run: docker push berk76/svjis-app:latest
